"""Add elements to allow interaction with twitter.

Revision ID: 012108e008ac
Revises: 08a26fe3588f
Create Date: 2017-02-27 15:28:44.860769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012108e008ac'
down_revision = '08a26fe3588f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_link', sa.Column('oauth_token', sa.String(), nullable=True))
    op.add_column('account_link', sa.Column('oauth_token_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_link', 'oauth_token_secret')
    op.drop_column('account_link', 'oauth_token')
    # ### end Alembic commands ###
